version: "3.9"

services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        env_file:
            - .env
        volumes:
            - ./data:/data/
